CREATE SEQUENCE geo_city_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE geo_district_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE geo_region_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE geo_city (id INT NOT NULL, region_id INT DEFAULT NULL, district_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, long DOUBLE PRECISION NOT NULL, lat DOUBLE PRECISION NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_297C2D3498260155 ON geo_city (region_id);
CREATE INDEX IDX_297C2D34B08FA272 ON geo_city (district_id);
CREATE TABLE geo_district (id INT NOT NULL, region_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_DF78232698260155 ON geo_district (region_id);
CREATE TABLE geo_region (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));