<?php

namespace Lists\OrganizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends EntityRepository
{
    /**
     * Searches organization by $q
     *
     * @param string  $q
     * @param string  $field
     *
     * @return mixed[]
     */
    public function getSearchQuery($q, $field)
    {
        $sql = $this->createQueryBuilder('b')
            ->where('lower(:field) LIKE :q')
            ->setParameter(':q', '%' . mb_strtolower($q, 'UTF-8') . '%')
            ->setParameter(':field', $field);

        return $sql->getQuery()->getResult();
    }
}
