<?php

namespace Lists\OrganizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoeaRepository extends EntityRepository
{
    /**
     * @param integer $id Organization.id
     *
     * @return mixed[]
     */
    public function getCoeaForContractorId($id)
    {
        /** @var \Doctrine\ORM\QueryBuilder $sql*/
        $sql = $this->createQueryBuilder('c')
                ->select('c.id')
                ->addSelect('s.name as scope')
                ->leftJoin('c.scope', 's')
                ->leftJoin('c.organization', 'o')
                ->where('c.organizationId = :organizationId')
                ->setParameter(':organizationId', $id)
                ->getQuery()
                ->getResult();

        return $sql;
    }
}
