<?php

namespace Lists\OrganizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationCurrentAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationCurrentAccountRepository extends EntityRepository
{
    /**
     * Searches organization by $q
     *
     * @param string  $q
     * @param integer $organizationId
     *
     * @return mixed[]
     */
    public function getSearchQuery($q, $organizationId = null)
    {
        $sql = $this->createQueryBuilder('a')
            ->where('lower(a.name) LIKE :q')
            ->setParameter(':q', '%' . mb_strtolower($q, 'UTF-8') . '%');
        if ($organizationId) {
            $sql->andWhere('a.organization = :organizationId')
                ->setParameter(':organizationId', $organizationId);
        }

        return $sql->getQuery()->getResult();
    }
    /**
     * Searches organization by $q
     *
     * @param integer $organizationId
     *
     * @return mixed[]
     */
    public function getBanks($organizationId)
    {
        $sql = $this->createQueryBuilder('a')
            ->select('b.mfo')
            ->addSelect('b.name')
            ->addSelect('b.id')
            ->innerJoin('a.bank', 'b')
            ->where('a.organization = :organizationId')
            ->setParameter(':organizationId', $organizationId)
            ->groupBy('b.id');

        return $sql->getQuery()->getResult();
    }
}
