<?php

namespace Lists\OrganizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
    public function getAllForSalesQuery($userId, $filters)
    {
        /** @var \Doctrine\ORM\QueryBuilder $sql*/
        $sql = $this->createQueryBuilder('o')
            ->select('o.id as organizationId', 'o.name as organizationName')
            ->addSelect('c.name as cityName')
            ->addSelect('r.name as regionName')
            ->addSelect('scope.name as scopeName')
            ->addSelect("
            array_to_string(
               ARRAY(
                  SELECT
                    CONCAT(CONCAT(u.lastName, ' '), u.firstName)
                  FROM
                    SDUserBundle:User u
                  LEFT JOIN u.organizations ou
                  WHERE ou.id = o.id
               ), ','
             ) as fullNames
            ")
            ->leftJoin('o.city', 'c')
            ->leftJoin('c.region', 'r')
            ->leftJoin('o.scope', 'scope')
            ->leftJoin('o.users', 'users')
            ->where('users.id = :userId')
            ->setParameter(':userId', $userId)
            ->orderBy('o.name', 'ASC');

        $this->processFilters($sql, $filters);

        $query = $sql->getQuery();

        $count = $this->getAllForSalesCount($userId, $filters);

        $query->setHint('knp_paginator.count', $count);

        return $query;
    }

    /**
     * Processes sql query depending on filters
     *
     * @param \Doctrine\ORM\QueryBuilder $sql
     * @param mixed[] $filters
     */
    public function processFilters(\Doctrine\ORM\QueryBuilder $sql, $filters)
    {
        if (sizeof($filters))
        {

            foreach($filters as $key => $value)
            {
                if (!$value)
                {
                    continue;
                }
                switch($key)
                {
                    case 'name':
                        $sql
                            ->andWhere("o.name LIKE :organizationName");

                        $sql->setParameter(':organizationName', '%' . $value);
                        break;
                    case 'scope':
                        if (isset($value[0]) && !$value[0])
                        {
                            break;
                        }
                        $sql->andWhere('scope.id in (:scopeIds)');
                        $sql->setParameter(':scopeIds', $value);
                        break;
                    case 'city':
                        if (isset($value[0]) && !$value[0])
                        {
                            break;
                        }
                        $sql->andWhere('c.id in (:cityIds)');
                        $sql->setParameter(':cityIds', $value);
                        break;
                    case 'users':
                        if (isset($value[0]) && !$value[0])
                        {
                            break;
                        }
                        $sql->andWhere('users.id in (:userIds)');
                        $sql->setParameter(':userIds', $value);
                        break;
                    /*case 'users':
                        if (isset($value[0]) && !$value[0])
                        {
                            break;
                        }
                        $query->andWhereIn('ou.user_id', $value);
                        break;*/
                }
            }
        }
    }

    public function getAllForSalesCount($userId, $filters)
    {
        $count = $this->getEntityManager()
            ->createQuery('
                SELECT
                    COUNT(o.id)
                FROM
                    ListsOrganizationBundle:Organization o
                INNER JOIN
                    o.users u
                WHERE
                    u.id = :userId
                ')
            ->setParameter(':userId', $userId)
            ->getSingleScalarResult();

        return $count;
    }

    /**
     * Searches organization by $q
     *
     * @param string $q
     *
     * @return mixed[]
     */
    public function getSearchQuery($q)
    {
        $sql = $this->createQueryBuilder('o')
            ->where('lower(o.name) LIKE :q')
            ->setParameter(':q', '%'. $q . '%')
            ->getQuery();

        return $sql->getResult();
    }
}
