<?php

namespace Lists\OrganizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
  public function getAllForSalesQuery()
  {
    $sql = $this->createQueryBuilder('o')
      ->select('o.id as organizationId', 'o.name as organizationName')
      ->addSelect('c.name as cityName')
      ->addSelect('r.name as regionName')
      ->addSelect('scope.name as scopeName')
      ->addSelect("
        array_to_string(
           ARRAY(
              SELECT
                CONCAT(CONCAT(u.lastName, ' '), u.firstName)
              FROM
                SDUserBundle:User u
              LEFT JOIN u.organizations ou
              WHERE ou.id = o.id
           ), ','
         ) as fullNames
      ")
      ->leftJoin('o.city', 'c')
      ->leftJoin('c.region', 'r')
      ->leftJoin('o.scope', 'scope')
      ->orderBy('o.name', 'ASC');

    $query = $sql->getQuery();

    $count = $this->getAllForSalesCount();

    $query->setHint('knp_paginator.count', $count);

    return $query;
  }

  public function getAllForSalesCount()
  {
    $count = $this->getEntityManager()
      ->createQuery('SELECT COUNT(o.id) FROM ListsOrganizationBundle:Organization o')
      ->getSingleScalarResult();

    return $count;
  }
}
