<?php

namespace Lists\OrganizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationServiceCoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationServiceCoverRepository extends EntityRepository
{
    /**
     * @param int $organizationId
     *
     * @return OrganizationServiceCover[]
     */
    public function getByOrganizationId($organizationId)
    {
        return $this->createQueryBuilder('osc')
            ->select('osc.id')
            ->addSelect('service.name as serviceName')
            ->addSelect('osc.isInterested')
            ->addSelect('osc.isWorking')
            ->addSelect('osc.evaluation')
            ->addSelect('osc.responsible')
            ->addSelect('osc.description')
            ->addSelect('osc.endDate')
            ->addSelect('competitor.name as competitorName')
            ->leftJoin('osc.service', 'service')
            ->leftJoin('osc.competitor', 'competitor')
            ->where('osc.organizationId = :organizationId')
            ->setParameter(':organizationId', $organizationId)
            ->getQuery()
            ->getArrayResult();
    }
}
