<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * HandlingMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingMessageRepository extends EntityRepository
{
    /**
     * getMessagesByHandlingId
     *
     */
    public function getMessagesByHandlingId($handlingId)
    {
        return $this->createQueryBuilder('hm')
            ->where('hm.handling_id = :handlingId')
            ->setParameter(':handlingId', $handlingId)
            ->getQuery()
            ->getResult();
    }

    /**
     * get Future messages
     *
     */
    public function getFutureMessages($userIds)
    {
        return $this->createQueryBuilder('hm')
            ->leftJoin('hm.user', 'user')
            ->leftJoin('hm.type', 'type')
            ->where('hm.createdate >= :createdate')
            ->andWhere('user.id in (:userIds)')
            ->setParameter(':createdate', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
            ->setParameter(':userIds', $userIds)
            ->getQuery()
            ->getResult();
    }
}
