<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandlingCompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingCompetitorRepository extends EntityRepository
{
    /**
     * @param int $handlingId
     *
     * @return HandlingCompetitor[]
     */
    public function getList($handlingId)
    {
        return $this->createQueryBuilder('hc')
            ->where('hc.handlingId = :handlingId')
            ->setParameter(':handlingId', $handlingId)
            ->getQuery()
            ->getResult();
    }
}
