<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandlingMessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingMessageTypeRepository extends EntityRepository
{
    static protected $list;

    public function getList()
    {
        if (!self::$list)
        {
            $handlingMessageTypes = self::createQueryBuilder('hmt')
                ->getQuery()
                ->getResult();

            self::$list = $handlingMessageTypes;
        }

        return self::$list;
    }
}
