<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandlingStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingStatusRepository extends EntityRepository
{
    /**
     * getListBySlug
     * 
     * @param string $slug
     *
     * @return array
     */
    public function getListBySlug($slug)
    {
        $sql = $this->createQueryBuilder('hs');
        if (in_array($slug, array('gos_tender'))) {
            $sql->where('hs.slug = :slug')
                ->setParameter(':slug', $slug);
        } else {
            $sql->where('hs.slug is null');
        }
        $sql->orderBy('hs.sortorder');
        
        return $sql->getQuery()->getResult();

    }
}
