<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandlingMessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingMessageTypeRepository extends EntityRepository
{
    protected static $list;

    /**
     * @return array
     */
    public function getList()
    {
        if (!self::$list) {
            $handlingMessageTypes = self::createQueryBuilder('hmt')
                ->getQuery()
                ->getResult();

            self::$list = $handlingMessageTypes;
        }

        return self::$list;
    }

    /**
     * @param array $slugs
     *
     * @return array
     */
    public function getListBySlug(array $slugs)
    {
        return self::createQueryBuilder('hmt')
            ->where('hmt.slug in (:slugs)')
            ->setParameter(':slugs', $slugs)
            ->orderBy('hmt.reportSortorder')
            ->getQuery()
            ->getResult();

    }
}
