<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandlingDogovorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingDogovorRepository extends EntityRepository
{
    /**
     * @param int $dogovorId
     *
     * @return HandlingDogovor[]
     */
    public function getList($dogovorId)
    {
        return $this->createQueryBuilder('hd')
            ->where('hd.dogovorId = :dogovorId')
            ->setParameter(':dogovorId', $dogovorId)
            ->leftJoin('hd.handling', 'handling')
            ->getQuery()
            ->getResult();
    }
}
