<?php

namespace Lists\HandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HandlingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandlingRepository extends EntityRepository
{
  public function getAllForSalesQuery($organizationId)
  {
    $sql = $this->createQueryBuilder('h')
      ->select('h.id as handlingId')
      ->addSelect('o.name as organizationName')
      ->addSelect('h.createdatetime as handlingCreatedatetime')
      ->addSelect('h.lastHandlingDate as handlingLastHandlingDate')
      ->addSelect('city.name as cityName')
      ->addSelect('scope.name as scopeName')
      ->addSelect('h.serviceOffered as handlingServiceOffered')
      ->addSelect('h.chance as handlingChance')
      ->addSelect('status.name as statusName')
      ->addSelect("
        array_to_string(
           ARRAY(
              SELECT
                CONCAT(CONCAT(u.lastName, ' '), u.firstName)
              FROM
                SDUserBundle:User u
              LEFT JOIN u.handlings hu
              WHERE hu.id = h.id
           ), ','
         ) as fullNames
      ")
      ->leftJoin('h.organization', 'o')
      ->leftJoin('o.city', 'city')
      ->leftJoin('o.scope', 'scope')
      ->leftJoin('h.status', 'status')
      ->where('o.id = :organizationId')
      ->orderBy('h.createdatetime', 'DESC');

    //$count = $this->getAllForSalesCount();

    /*$query = $this->getEntityManager()
      ->createQuery('
            SELECT
              o, c, r FROM
            ListsOrganizationBundle:Organization o
            LEFT JOIN o.city c
            LEFT JOIN c.region r
            ');*/

    $sql->setParameter(':organizationId', $organizationId);

    $query = $sql->getQuery();

    $count = $this->getAllForSalesCount($organizationId);

    $query->setHint('knp_paginator.count', $count);

    return $query;
  }

  public function getAllForSalesCount($organizationId)
  {
    $count = $this->getEntityManager()
      ->createQuery('SELECT COUNT(h.id) FROM ListsHandlingBundle:Handling h WHERE h.organization_id = :organizationId')
      ->setParameter(':organizationId', $organizationId)
      ->getSingleScalarResult();

    return $count;
  }
}
