<?php

namespace ITDoors\SipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallRepository extends EntityRepository
{
}
