<?php

namespace ITDoors\CalculateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalculatorItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculatorItemRepository extends EntityRepository
{
}
