<?php

namespace Lists\LookupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LookupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LookupRepository extends EntityRepository
{
    const KEY__SCOPE = 'scope';

    /**
     * Returns choices for scope
     */
    public function getOnlyScopeQuery()
    {
        return $this->getLookupByLukeyQuery(self::KEY__SCOPE);
    }

    /**
     * Get lookup by lukey
     *
     * @param string $lukey
     *
     * @return \Doctrine\ORM\Query
     */
    public function getLookupByLukeyQuery($lukey)
    {
        $query = $this->createQueryBuilder('l')
            ->where('l.lukey = :lukey')
            ->setParameter(':lukey', $lukey);

        return $query;
    }
}
