<?php

namespace Lists\CompanystructureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanystructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanystructureRepository extends EntityRepository
{
    /**
     * Searches city by $q
     *
     * @param string $q
     *
     * @return mixed[]
     */
    public function getSearchQuery($q)
    {
        $sql = $this->createQueryBuilder('c')
            ->where('lower(c.name) LIKE :q')
            ->setParameter(':q', mb_strtolower($q, 'UTF-8') . '%')
            ->getQuery();

        return $sql->getResult();
    }
}
