<?php

namespace Lists\DogovorBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * DogovorDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogovorDepartmentRepository extends EntityRepository
{
    /**
     * Return all departments depending on dogovor id
     *
     * @param int $dogovorId
     *
     * @return Query
     */
    public function getAllByDogovorIdQuery($dogovorId)
    {
        $query = $this->createQueryBuilder('dd')
            ->select('dd.id as id')
            ->addSelect('dd.createdatetime as createdatetime')
            ->addSelect('dogovor.number as dogovorNumber')
            ->addSelect("CONCAT(CONCAT(dopDogovor.id, ' '), dopDogovor.number) as dopDogovorString")
            ->addSelect("CONCAT(CONCAT(city.name, '|'), d.address) as department")
            ->addSelect("CONCAT(CONCAT(user.lastName, ' '), user.firstName) as creatorFullName")
            ->addSelect('dd.comment as comment')
            ->leftJoin('dd.dogovor', 'dogovor')
            ->leftJoin('dd.dopDogovor', 'dopDogovor')
            ->leftJoin('dd.department', 'd')
            ->leftJoin('d.city', 'city')
            ->leftJoin('dd.user', 'user')
            ->where('dd.dogovorId = :dogovorId')
            ->setParameter(':dogovorId', $dogovorId)
            ->getQuery();

        return $query;
    }

    /**
     * Checks if record exists by dogovorId dopDogovorId departmentId
     *
     * @param int $dogovorId
     * @param int $dopDogovorId
     * @param int $departmentId
     *
     * @return boolean
     */
    public function isExists($dogovorId, $dopDogovorId, $departmentId)
    {
        $elements = $this->createQueryBuilder('dd')
            ->where('dd.dogovorId = :dogovorId')
            ->andWhere('dd.dopDogovorId = :dopDogovorId')
            ->andWhere('dd.departmentId = :departmentId')
            ->setParameters(array(
                ':dogovorId' => $dogovorId,
                ':dopDogovorId' => $dopDogovorId,
                ':departmentId' => $departmentId,
            ))
            ->getQuery()
            ->getResult();

        return sizeof($elements) ? true: false;
    }
}
