<?php

namespace Lists\DogovorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DogovorCompanystructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogovorCompanystructureRepository extends EntityRepository
{
}
