<?php

namespace Lists\DogovorBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * DogovorDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogovorDepartmentRepository extends EntityRepository
{
    /**
     * Return all departments depending on dogovor id
     *
     * @param int $dogovorId
     *
     * @return Query
     */
    public function getAllByDogovorIdQuery($dogovorId)
    {
        $query = $this->createQueryBuilder('dd')
            ->where('dd.dogovorId = :dogovorId')
            /*->leftJoin('dd.department', 'd')
            ->leftJoin('d.city', 'city')*/
            ->setParameter(':dogovorId', $dogovorId)
            ->getQuery();

        return $query;
    }

    /**
     * Checks if record exists by dogovorId dopDogovorId departmentId
     *
     * @param int $dogovorId
     * @param int $dopDogovorId
     * @param int $departmentId
     *
     * @return boolean
     */
    public function isExists($dogovorId, $dopDogovorId, $departmentId)
    {
        $elements = $this->createQueryBuilder('dd')
            ->where('dd.dogovorId = :dogovorId')
            ->andWhere('dd.dopDogovorId = :dopDogovorId')
            ->andWhere('dd.departmentId = :departmentId')
            ->setParameters(array(
                ':dogovorId' => $dogovorId,
                ':dopDogovorId' => $dopDogovorId,
                ':departmentId' => $departmentId,
            ))
            ->getQuery()
            ->getResult();

        return sizeof($elements) ? true: false;
    }
}
