<?php

namespace SD\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskUserRoleRepository extends EntityRepository
{
    /**
     * @param integer $userId
     * @param string  $role
     *
     * @return integer
     */
    public function countTasksByRoleAndUser($userId, $role)
    {
        $sql = $this->createQueryBuilder('tur')
            ->select('COUNT(tur.id)')
            ->leftJoin('tur.role', 'r')
            ->leftJoin('tur.user', 'u')
            ->where('u.id = :userId')
            ->setParameter(':userId', $userId);

        if ($role) {
            $sql->andWhere('r.name = :role')
                ->setParameter(':role', $role);
        }

        return $sql->getQuery()->getSingleScalarResult();
    }
}
