<?php

namespace SD\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskEndDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskEndDateRepository extends EntityRepository
{
}
