<?php

namespace Lists\GrafikBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrafikTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrafikTimeRepository extends EntityRepository
{
    public function getCoworkerHoursDayInfo($year, $month, $day, $idDepartment, $idCoworker) {
        $result = $this->createQueryBuilder('gt')
            ->leftJoin('gt.department', 'd')
            ->leftJoin('gt.departmentPeople', 'dp')
            ->andWhere('gt.month = :month')
            ->setParameter('month', $month)
            ->andWhere('gt.day = :day')
            ->setParameter('day', $day)
            ->andWhere('gt.year = :year')
            ->setParameter(':year', $year)
            ->andWhere('d.id = :idDepartment')
            ->setParameter(':idDepartment', $idDepartment)
            ->andWhere('dp.id = :idCoworker')
            ->setParameter(':idCoworker', $idCoworker)
            ->getQuery()
            ->getResult();

        return $result;
    }

}
