<?php

namespace SD\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StuffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffRepository extends EntityRepository
{
}
