<?php

namespace SD\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Get Only stuff
     *
     * @return \Doctrine\ORM\Query
     */
    public function getOnlyStaff()
    {
        return $this->createQueryBuilder('u')
            ->select('u', 'staff')
            ->innerJoin('u.staff', 'staff')
            ->orderBy('u.lastName', 'ASC');

    }

    /**
     * Get users by organization
     *
     * @param int $organizationId
     *
     * @return \Doctrine\ORM\Query
     */
    public function getOrganizationUsersQuery($organizationId)
    {
        return $this->createQueryBuilder('u')
            ->select('u', 'staff')
            ->innerJoin('u.staff', 'staff')
            ->innerJoin('u.organizations', 'organizations')
            ->where('organizations.id = :organizationId')
            ->setParameter(':organizationId', $organizationId);
    }

    /**
     * Get users by handling
     *
     * @param int $handlingId
     *
     * @return \Doctrine\ORM\Query
     */
    public function getHandlingUsersQuery($handlingId)
    {
        return $this->createQueryBuilder('u')
            ->select('u', 'staff')
            ->innerJoin('u.staff', 'staff')
            ->innerJoin('u.handlings', 'handlings')
            ->where('handlings.id = :handlingId')
            ->setParameter(':handlingId', $handlingId);
    }
}
