<?php

namespace Lists\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModelContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelContactRepository extends EntityRepository
{
    const MODEL_ORGANIZATION = 'organization';

    public function getMyOrganizationsContacts($userIds, $organizationId)
    {
        if (is_array($userIds) && $userIds)
        {
            $userIds = array($userIds);
        }

        return $this->createQueryBuilder('mc')
            ->select('mc')
            /*->select('mc.firstName as firstName')
            ->addSelect('mc.lastName as lastName')
            ->addSelect('mc.middleName as middleName')*/
            ->addSelect('o.name as organizationName')
            ->addSelect("CONCAT(CONCAT(u.lastName, ' '), u.firstName) as creatorFullName")
            ->leftJoin('mc.user', 'u')
            ->leftJoin('ListsOrganizationBundle:Organization', 'o', 'WITH', 'o.id = mc.modelId')
            ->leftJoin('o.users', 'users')
            ->where('mc.modelName = :modelName')
            ->andWhere('o.id = mc.modelId')
            ->andWhere('users.id in (:userIds)')
            ->orderBy('o.name')
            ->setParameter(':userIds', $userIds)
            ->setParameter(':modelName', self::MODEL_ORGANIZATION);
    }
}
