<?php

namespace Lists\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModelContactLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelContactLevelRepository extends EntityRepository
{
}
