<?php

namespace ITDoors\ControllingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceActRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceActRepository extends EntityRepository
{
    /**
     * getSum
     * 
     * @param integer $invoiceId
     * 
     * @return integer
     */
    public function getSum ($invoiceId)
    {

        return $this->createQueryBuilder('a')
            ->select('SUM(ad.summa)')
            ->join('a.detals', 'ad')
            ->where('a.invoiceId = :invoiceId')
            ->setParameter(':invoiceId', $invoiceId)
            ->getQuery()->getOneOrNullResult();
    }
}
