<?php

namespace ITDoors\ControllingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceMessageRepository extends EntityRepository
{
        /**
     * Returns results for interval future invoice
     *
     * @param int $invoiceid Description
     *
     * @return mixed[]
     */
    public function getInvoiceMessages($invoiceid)
    {
        $res = $this->createQueryBuilder('i_m')
            ->select('i_m.note')
            ->addSelect('i_m.id')
            ->addSelect('i_m.createdate')
            ->addSelect('u.firstName')
            ->addSelect('u.lastName')
            ->addSelect('c.firstName as cfirstName')
            ->addSelect('c.lastName as clastName')
            ->innerJoin('i_m.user', 'u')
            ->leftJoin('i_m.contact', 'c')
            ->andWhere("i_m.invoiceId = :invoiceId")
            ->setParameter(':invoiceId', $invoiceid)
            ->orderBy('i_m.createdate', 'DESC')
            ->getQuery();

        return $res->getResult();
    }
}
