<?php

namespace Lists\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsTypeRepository extends EntityRepository
{
}
