<?php

namespace ITDoors\OperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentOrganizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentOrganizerRepository extends EntityRepository
{

    public function getReports()
    {

        $sql = $this->createQueryBuilder('comment')
            ->select('t.name as typeName')
            ->addSelect('o.name as organizationName')
            ->addSelect('d.name as departmentName')
            ->addSelect('d.address as departmentAddress')
            ->addSelect('organizer.startDatetime as startDatetime')
            ->addSelect('organizer.endDatetime as endDatetime')
            ->addSelect('CONCAT(CONCAT(u.lastName, \' \'), u.firstName) as userName')
            ->addSelect('comment.value as commentValue')
            ->addSelect('comment.createDatetime as commentDate')
            ->leftJoin('comment.organizer', 'organizer')
            ->leftJoin('comment.user', 'u')
            ->leftJoin('organizer.department', 'd')
            ->leftJoin('d.organization', 'o')
            ->leftJoin('organizer.type', 't');

        return $sql->getQuery()->getResult();
    }
}
