<?php

namespace ITDoors\OperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentOrganizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentOrganizerRepository extends EntityRepository
{
}
