<?php
namespace Lists\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsFosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRoleRepository extends EntityRepository
{
}
