<?php

namespace Lists\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsFosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsFosUserRepository extends EntityRepository
{
    /**
     * getNotifications
     * 
     * @param integer $id User.id
     * 
     * @return array
     */
    public function getNotifications($id)
    {
        $sql = $this->createQueryBuilder('nfu');

        $sql->innerJoin('nfu.news', 'n', 'WITH', 'n.type = :type')
            ->setParameter(':type', 'notification');
            

        return $sql->orderBy('n.datePublick', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
