<?php

namespace Lists\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{

    /**
     * Returns results for interval future invoice
     * 
     * @param integer $id Article.id
     * 
     * @return array
     */
    public function getVoteForArticle($id)
    {
        $sql = $this->createQueryBuilder('v');

        $res = $sql
            ->select('SUM(v.value) as sumVote')
            ->addSelect('COUNT(v.id) as countVote')
            ->where('v.modelId = :id')
            ->andwhere('v.modelName = :text')
            ->setParameter(':id', $id)
            ->setParameter(':text', 'article')
            ->getQuery()
            ->getSingleResult();

        return $res;
    }

    /**
     * Returns results for interval future invoice
     * 
     * @param integer $id Article.id
     * 
     * @return array
     */
    public function getVoites($id)
    {
        $sql = $this->createQueryBuilder('v');

        $res = $sql
            ->select('v.value')
            ->addSelect('v.dateCreate')
            ->addSelect('u.firstName')
            ->addSelect('u.lastName')
            ->addSelect('u.middleName')
            ->innerjoin('v.user', 'u')
            ->where('v.modelId = :id')
            ->andwhere('v.modelName = :text')
            ->setParameter(':id', $id)
            ->setParameter(':text', 'article')
            ->orderBy('v.dateCreate', 'DESC')
            ->getQuery()
            ->getResult();

        return $res;
    }
}
