<?php

namespace SD\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * 
     * @param integer $userId
     * @param string  $type
     * 
     * @return array
     */
    public function getPersonalTask ($userId, $type)
    {
        return $this->createQueryBuilder('t')
            ->select('t.id')
            ->addSelect('t.title')
            ->addSelect('t.startDateTime')
            ->addSelect('t.stopDateTime')

            ->where('t.userId = :userid')
            ->where('t.taskType = :type')
//                
            ->setParameter(':userid', $userId)
            ->setParameter(':type', $type)
                
            ->getQuery()
            ->getResult();
    }
}
