<?php

namespace Lists\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectElectronicTradingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectElectronicTradingRepository extends EntityRepository
{
     /**
     * getProjectSimple
     * 
     * @param integer $id
     *
     * @return Query
     */
    public function getProjectElectronicTrading($id)
    {
        /** @var \Doctrine\ORM\QueryBuilder $sql */
        $sql = $this->createQueryBuilder('p');

        // where
        $sql->where('p.id = :id')
            ->setParameter(':id', $id);

        $query = $sql->getQuery();

        return $query->getSingleResult();
    }
}
