<?php

namespace Lists\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectSimpleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectSimpleRepository extends EntityRepository
{
    /**
     * getProjectSimple
     * 
     * @param integer $id
     *
     * @return Query
     */
    public function getProjectSimple($id)
    {
        /** @var \Doctrine\ORM\QueryBuilder $sql */
        $sql = $this->createQueryBuilder('ps');

        // where
        $sql->where('ps.id = :id')
            ->setParameter(':id', $id);

        $query = $sql->getQuery();

        return $query->getSingleResult();
    }
}
