<?php

namespace Lists\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
     /**
     * Searches service by $ids
     *
     * @param mixed[] $ids
     *
     * @return mixed[]
     */
    public function getGyIds($ids)
    {
        $sql = $this->createQueryBuilder('s');

        $sql
            ->where($sql->expr()->in('s.id', ':ids'))
            ->setParameter(':ids', $ids);

        return $sql->getQuery()->getResult();
    }
}
